### ISSUE TITLE
header 작업

### ISSUE THREAD

**Issue by euan-lee** [Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-FE#105]
## 작업 내용 header작업을 완료하려 합니다. 

- [ ] header 업체용
- [ ] header 고객용

## 세부 작업 기간 0.5md

 0.5md

늦어도 내일 2시 전까지는 완수할것 같네용

**Comment by jgjgill** [comment]
변경되는 작업 순서 3차 스프린트 작업 목록 #76 에 업데이트 해주시면 감사하겠습니다..! 🙇‍♂️
