### ISSUE TITLE
색상 변수 정의하기

### ISSUE THREAD

**Issue by Lim-JiSeon** [Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-FE#17]
## 내용 설명
- 디자인 과정에서 색상을 정의합니다.
- 정의된 색상들을 환경 변수로 정리합니다. (constants .폴더)

## 작업 내용

- [ ] 서비스 색상표 정의하기(피그마 작업과 함께 진행)
- [ ] 색상표 환경 변수 정의하기

## 세부 작업 기간
2md (디자인 : 1.5md, 색상표 정의 : 30분)

[참고 코드 1](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/blob/main/src/styles/light-theme.scss)
[참고 코드 2](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/blob/main/src/styles/color-themes.scss)

**Comment by jgjgill** [comment]
참고하시면 좋을 것 같습니다..!
[Theme Configuration](https://tailwindcss.com/docs/theme)
