### ISSUE TITLE
3차 스프린트 작업 목록

### ISSUE THREAD

**Issue by jgjgill** [Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-FE#76]
## 내용 설명

3차 스프린트 작업 목록입니다.

## 작업 내용

- [x] #84 
- [x] #111  
- [x] #112 
- [x] #87 
- [x] #89 
- [x] #113 
- [x] 로그아웃 페이지
- [x] #133
- [x] #92 
- [x] #96 
- [x] #135 
- [x] #109 
- [x] #98
- [x] #99
- [x] #116

**Comment by Lim-JiSeon** [comment]
11월 6일(월) 
- [x] MIL 작성하기
- [x] 상품 CRUD 디자인하기
- [x] 업체 등록 페이지 깃허브 피드백 반영하기
- [x] formik 문서화 작업하기

**Comment by Lim-JiSeon** [comment]
11월 7일(화) 
- [x] 토글 스위치 컴포넌트 만들기
- [ ] 영업 상태 조회 api 연결하기(추후 작업)
- [x] 업체 등록 페이지 깃허브 피드백 반영하기(연장)
- [x] 상품 주문 페이지 디자인 작업하기

**Comment by Lim-JiSeon** [comment]
11월 8일(수) 
- [x] 영업 상태 컴포넌트 만들기
- [x] 업체 등록 여부 모달창 띄우기 작업하기
- [x] 등록된 상품 조회하기 페이지 디자인 작업하기
- [x] 주문 내역 고객 & 업체 디자인 작업하기

**Comment by Lim-JiSeon** [comment]
11월 9일(목) 
- [x] 등록된 상품 조회하기 페이지 디자인 작업하기(연장)
- [x] 상품 주문 페이지 디자인 작업하기(연장)
- [x] 업체 상세 페이지 디자인 작업하기
- [x] 영업 상태 api 연결하기(개발 환경에서만 테스트)

**Comment by jgjgill** [comment]
회원가입 폼 api, 내 가게 정보 api, 지도 마커 api는 다음 스프린트로 미루고 **회원가입 폼, 상품 관련 디자인**으로 작업 순서 변경하겠습니다!

**Comment by Lim-JiSeon** [comment]
11월 10일(금) 
- [x] 장바구니 페이지 디자인 작업하기
- [x] 장바구니 주문 정보 컴포넌트 구현하기
- [x] 장바구니 안내 사항 컴포넌트 구현하기
- [x] 색상코드 추가 및 로컬스토리지 네이밍 컨벤션 추가하기

api 작업을 추후로 미룬 뒤 컴포넌트 작업을 먼저 하기 위해 스프린트 목록을 수정했습니다.
